### PR TITLE
fix: issue 4/player permissions

### LINKED ISSUE #4: fix: Use predefined `playerPermissions` for players in lobby channels.
`playerPermissions` was added as part of a permissions group in #2 for more consistent handling of overwrites, however they weren't used everywhere. _They will also need refinement, but that will be for another task._
https://github.com/TinkerStorm/interaction-prototypes/blob/232ff467bb4ad6c4a11c45c3db7bfeca2437182f/src/util/permissions.ts#L24-L29

---

### Occurances:

https://github.com/TinkerStorm/interaction-prototypes/blob/232ff467bb4ad6c4a11c45c3db7bfeca2437182f/src/components/new-game.ts#L45-L53
https://github.com/TinkerStorm/interaction-prototypes/blob/232ff467bb4ad6c4a11c45c3db7bfeca2437182f/src/components/accept.ts#L57
https://github.com/TinkerStorm/interaction-prototypes/blob/232ff467bb4ad6c4a11c45c3db7bfeca2437182f/src/components/join.ts#L91

### PR DESCRIPTION
**Pull request by sudojunior**
fixes #4 by using predefined player permissions from `util/permissions.ts`

### CODE REVIEW

File: src/util/permissions.ts [hunk 1]
```diff
@@ -1,37 +1,47 @@
...
+// all required permissions
+export const allChannelPermissions = new Permissions([
+  managerPermissions,
+  'MANAGE_MESSAGES',
+  'MANAGE_ROLES',
+  'EMBED_LINKS',
+  'READ_MESSAGE_HISTORY',
+  'USE_EXTERNAL_EMOJIS'
+  // 'CONNECT',
+  // 'SPEAK'
```
Comment (sudojunior) [inline src/util/permissions.ts:31]: Voice channel permissions are not required at this stage, but channel management strategies may change in the near future (i.e. the option to setup the handler to create text or voice channels).

> Voice channels, if created using this bot, would not be _supervised_ due to the extensive bandwidth required to remain in a channel - regardless of how many would be talking in one game, absolute silence in another, and the plausible scenario of managing multiple games at once.

```suggestion
```

File: src/util/permissions.ts [hunk 2]
```diff
@@ -1,37 +1,47 @@
...
+  'CREATE_INSTANT_INVITE',
+
+  // Text permissions
+  'ATTACH_FILES',
+  'MENTION_EVERYONE',
+
+  // Voice permissions
+  'CONNECT',
+  'SPEAK'
+]);
```
Comment (sudojunior) [inline src/util/permissions.ts:47]: Everything else gets a bit blurred here, since it depends if the bot has any of them to begin with... nevertheless I believe it should stay as part of consistency to determine what permissions are necessary to have it run vs. what may be unnecessary for its core functions (more quality over quantity, rather than having to micromanage - just use category inheritance _noting that user overwrites take precedence over that of role counterparts_).

File: src/components/new-game.ts [hunk 3]
```diff
@@ -12,6 +12,7 @@ import {
 import { pickPhonetic } from '../util/fakerExtended';
 import { buildPost, createGame, games, IGame, lobbyChannels } from '../util/game';
 import { managerPermissions, observerPermissions } from '../util/permissions';
+import { ComponentKeys } from './index';
```
Comment (sudojunior) [inline src/components/new-game.ts:15]: Whoops...

File: src/components/decline.ts [hunk 4]
```diff
@@ -1,6 +1,7 @@
 import { Client as ErisClient } from 'eris';
 import { ComponentContext } from 'slash-create';
 
+import { undi } from '../util/common';
```
Comment (sudojunior) [inline src/components/decline.ts:4]: `undi` is derived from a blargbot tag, which I was responsible for creating. The principle remains the same to generate a consistent user string format and fill in the gaps for the library interfaces.

https://github.com/TinkerStorm/interaction-prototypes/blob/7ea20d2eec1bd98a02068d7074504483a9c0a268/src/util/common.ts#L40-L47

**Review by sudojunior — COMMENTED** [review]
Failover requests are more important here to guarantee the bot can continue running if it fails to send a message to a user. At this time, it does not remember if a user had their DMs blocked (either no mutual guilds that allow the bot to send messages or just directly blocked).

Preconditions may be explored to stop this from happening repeatedly, but it is not a primary focus or concern with the scale it is deployed to at this time.
